Added Romanian translations.
zopefoundation/z3c.form pull request #123
Opened 2024-08-12 10:33 UTC by jladage

Just added translations for Romanian language.

2024-08-13 06:06 UTC, icemac commented
Thank you for your contribution.

According to the contributing policies of the zopefoundation organization you need to sign a contributor agreement before any non-trivial change can be merged. For details please consult the [Contributing guidelines for zopefoundation projects](https://github.com/zopefoundation/.github/blob/master/CONTRIBUTING.md).

2024-08-13 06:07 UTC, icemac commented
@MrTango Is your Romanian good enough to review these translations?

2024-08-13 09:12 UTC, jladage commented
Hi Micheal,I signed a contributing license for Plone in 2007. Will that do? Or do you want a new one just for Zope which uses Plone’s as I understand.Kind regards,Jean-Paul LadageOn 13 Aug 2024, at 07:08, Michael Howitz ***@***.***> wrote:﻿
@MrTango Is your Romanian good enough to review these translations?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-08-14 06:11 UTC, icemac commented
@jladage When you sign a Zope contributor agreement, you will get a Member of the `zopefoundation` project, this is the way I see that the agreement was signed and it will allow you to merge yout PR after successful review.

So I cannot answer your question. I'd suggest either to ask someone of the Plone Foundation or just sign a contributor agreement for Zope.

2024-10-02 06:52 UTC, icemac commented
@jladage You are now listed as `Member` are you also able to merge yourself?

2024-10-03 11:01 UTC, jladage commented
@icemac nope, at least not if nobody is able to review the Romanian translations I created with deepl.

2024-10-03 15:10 UTC, davisagli commented
@avoinea Would you like to help review this or ask someone else to?

2024-10-03 16:26 UTC, avoinea requested changes

2024-10-03 16:26 UTC, avoinea commented on src/z3c/form/locales/ro/LC_MESSAGES/z3c.form.po
> +"selectat"
```suggestion
"content, selected"
```

2024-10-03 16:26 UTC, avoinea commented on src/z3c/form/locales/ro/LC_MESSAGES/z3c.form.po
> +msgstr "Mesaj fără valoare"
```suggestion
msgstr "Mesaj lipsă valoare"
```

2024-10-03 16:26 UTC, avoinea commented on src/z3c/form/locales/ro/LC_MESSAGES/z3c.form.po
> +"Un steag setat atunci când cel puțin un câmp este marcat ca fiind obligatoriu"
```suggestion
"Setat atunci când cel puțin un câmp este marcat ca fiind obligatoriu"
```

2024-10-03 16:26 UTC, avoinea commented on src/z3c/form/locales/ro/LC_MESSAGES/z3c.form.po
> +msgstr "Contextul în care este afișat widget-ul."
```suggestion
msgstr "Contextul în care este afișat widgetul."
```

2024-10-21 09:20 UTC, jladage commented
Hi @avoinea, I merged your translation suggestions. Could you please review once more so I can merge?

2024-10-21 09:49 UTC, avoinea approved these changes

2024-10-21 10:34 UTC, avoinea approved these changes

2024-10-21 17:51 UTC, jladage commented
@icemac the test coverage is currently blocking this request from merging. I'm not familiar enough with the code to understand why. Do we test translations? Are our changes the result of the test coverage problem?

2024-10-22 06:39 UTC, icemac commented
@jladage The translations are not part of the coverage and are not tested. I saw a drop in coverage on serveral packages, probably because of a new version of the `coverage` package.

I'll merge this PR now and tackle the coverage problem later on.

2024-10-22 06:40 UTC, icemac approved these changes

2024-10-22 06:40 UTC, merged